name = "unbound-presence-do"
main = "src/index.ts"
compatibility_date = "2025-02-01"
workers_dev = true

[vars]
ENVIRONMENT = "development"



[[durable_objects.bindings]]
name = "PRESENCE_DO"
class_name = "PresenceDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PresenceDurableObject"]
