name = "unbound-presence-do"
main = "src/index.ts"
compatibility_date = "2025-02-01"
workers_dev = true

[vars]
PRESENCE_DO_TOKEN_SIGNING_KEY = ""
PRESENCE_DO_INGEST_TOKEN = ""

[[durable_objects.bindings]]
name = "PRESENCE_DO"
class_name = "PresenceDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["PresenceDurableObject"]
